# Generated by Django 3.2.12 on 2022-05-07 14:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField(max_length=1000, verbose_name='Blog İçerik')),
                ('image', models.ImageField(blank=True, null=True, upload_to='kisiresmi/', verbose_name='kisi Resmi Ekleyin')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi ')),
            ],
        ),
    ]
